### ISSUE TITLE
Implement the necessary traits for collections

### ISSUE THREAD

**Issue by pickfire** [fitzgen/bumpalo#102]
```rust
error[E0277]: a value of type `bumpalo::collections::Vec<'_, (&[u8], u64)>` cannot be built from an iterator over elements of type `(&[u8], u64)`
  --> main.rs:73:61
   |
73 |     let mut ordered: Vec<(&[u8], u64)> = counts.into_iter().collect();
   |                                                             ^^^^^^^ value of type `bumpalo::collections::Vec<'_, (&[u8], u64)>` cannot be built from `std::iter::Iterator<Item=(&[u8], u64)>`
   |
   = help: the trait `FromIterator<(&[u8], u64)>` is not implemented for `bumpalo::collections::Vec<'_, (&[u8], u64)>`
```

`counts` have type `HashMap<&'bump [u8], u64>`

Can we implement `FromIter` and other trait to support `collect` for feature parity with standard library?

**Comment by fitzgen** [comment]
It won't work because you need a reference to the `Bump` to collect them into.

[`Extend`](https://docs.rs/bumpalo/3.6.1/bumpalo/collections/vec/struct.Vec.html#method.extend) is implemented, however, and side steps this problem since an already-constructed `bumpalo::collections::Vec` has a reference to the `Bump` internally.
