### ISSUE TITLE
3.11.1 broke backwards-compatibility

### ISSUE THREAD

**Issue by muglug** [fitzgen/bumpalo#182]
[This fix](https://github.com/fitzgen/bumpalo/commit/6e10b0fa8d24d7c31b3c234f75215fa68c252e02) changed what I _think_ is a public API.

Should that have landed in a major version?

**Comment by fitzgen** [comment]
It's a slightly tricky thing. It is technically a breaking change, but since it is a security fix I wanted it to be on the 3.x series. I feel like there isn't really an absolute right answer for what to do in this situation and people could argue either way. I made a choice and am going to stick with that choice. Hope it wasn't too much of a hassle for you.
