### ISSUE TITLE
Anything to do before making a new breaking release?

### ISSUE THREAD

**Issue by fitzgen** [fitzgen/bumpalo#51]
We have had a bunch of great work committed to master that I'd like to publish, and some of it is breaking (the reversal of bump direction, for example). Because it is breaking, I'd like to double check that we aren't missing any breaking changes that we can coalesce into a single release, rather than eventually doing multiple breaking releases.

@TethysSvensson, anything else on your radar? Anything else needed for your flatbuffers effort?

cc @vorner 

----------------------

### TODO

* [ ] Fill out the CHANGELOG
* [ ] Explain how to update for the breaking changes
* [ ] other stuff?

-----------------------

<details>

<summary>Commits since the last release</summary>

* 1ade235 Merge pull request #50 from vorner/alloc_str
* b633583 Bump::alloc_str
* e61f3a4 Fix license copy-pasta
* 33f4bcf Merge pull request #44 from TethysSvensson/slice-allocations
* f18e9f1 Add tests for alloc_slice_fill
* b70b52a Change the argument order to make alloc_slice_fill_copy consistent with alloc_slice_fill_with
* a3781df Fix ZSTs in alloc and dealloc instead of only in the slice functions
* 017926b De-duplicate the code and add a two new functions
* 0c7ed93 Update src/lib.rs
* e01652f We probably should not remove the padding at the end of an array
* 14446bc Fix up the argument order in the docs as well
* 941b3b7 Fix up the argument order
* 2a3c79e Implement some more slice allocation functions
* ca32821 Merge pull request #48 from TethysSvensson/issue-46-alt
* abacc21 Fix the broken realloc test
* 9709ff8 Use compile time assertions instead of a const fn max
* 77ebbc1 Simplify some const definitions
* d15154b Update the allocation strategy again
* aad669a Even better strategy
* e82ab18 Better doubling strategy
* ab73145 Fix for #46
* 3d8dc44 Merge pull request #45 from fitzgen/alloc-layout-slow-alignment
* 60261bd Make sure to align pointers in `alloc_layout_slow`
* 7032a99 Merge pull request #42 from TethysSvensson/iter-order
* 1cc8071 Reverse the order of the chunks in iter_allocated_chunks and each_allocated_chunk
* 96841a6 Merge pull request #40 from fitzgen/remove-dbg
* 3e6ee5c Remove leftover `dbg!` from debugging
* d261433 Merge pull request #39 from zhiburt/remove_commented_code_in_lib
* 36a3f8a Remove commented block in test block.
* 38054c7 Merge pull request #37 from fitzgen/bump-downwards
* 2f33d05 Bump downwards
* f7b9e2e Update to criterion 0.3
* c0fa76c Merge pull request #36 from andylokandy/extend_reserve
* 35291d6 Merge pull request #35 from TethysSvensson/better-realloc
* 0f5a5e2 Use a realloc algorithm closer to the previous one, since it was easier to reason about
* f8eb1fb Reserve space before Vec::extend()
* 370d37a Improve the dealloc and realloc functions to more agressively reuse memory
* 7cd9452 Merge pull request #34 from TethysSvensson/always-no_std
* 43e66ae Always compile as a no_std crate
* d62674c Merge pull request #33 from TethysSvensson/reset-save-last
* 0857024 Reimplement reset to keep the last chunk instead of the first
* 2cb090d Merge pull request #32 from TethysSvensson/clippy
* 2d70b69 Lint cleanup
* 9b22a64 Merge pull request #29 from TethysSvensson/with-capacity
* 71b5e88 Add test for with_capacity
* cf19e20 Simplify the implementation a bit
* 92d2842 Add a with_capacity function
* 7ac4a53 cargo fmt
* ee4fa63 Merge pull request #31 from fitzgen/fix-bad-debug-assertion
* 7a2c28b Check for some potential overflows and fix buggy assertion
* 1fec3b8 Merge pull request #30 from TethysSvensson/iterator
* 9f2d375 Re-introduce each_allocated_chunk for backwards compatibility
* 3b42fd8 Update src/lib.rs
* 68c1e4d Update src/lib.rs
* c89d03d Update src/lib.rs
* 75bdf16 Update src/lib.rs
* cfd01ae Update src/lib.rs
* 96ab7cc Replace each_allocated_chunk function with iter_allocated_chunks function
* d823726 Merge pull request #24 from rtfeldman/patch-1
* d5a3a10 Fix inaccurate documentation URL in Cargo.toml

</details>

**Comment by TethysSvensson** [comment]
I think we should consider whether this is the right time to remove deprecated stuff. The things I know of are:

* The `std` feature flag, which no longer does anything
* The function `each_allocated_chunk`

Otherwise I think this would be a really nice time to do a new release, and I cannot think of any important improvements right now.

I can think of a few non-important ones improvements, that I might be interested in exploring at some point, but even then I do not think any of them would break backwards compatibility.

* I think we could potentially improve the strategy for how to increase the chunk size -- that is if somebody is willing to benchmarks/code dives to figure out what is "best".
* I think it would be interesting to explore an API for using bumpalo without depending on `alloc` for e.g. tiny embedded applications. I am thinking it might be possible to have an initializer which simply contains a `&mut [u8]` internally without having a huge amount of code duplication.

I do not have any current needs for any of them though, so I think it is unlikely that I will get around to exploring them in the near future (or ever).

**Comment by TethysSvensson** [comment]
Also, do you think that #2 and #12 should somehow be resolved before you to a release? Or do you just want to keep them open for now?

**Comment by TethysSvensson** [comment]
@fitzgen Are you still planning on doing a release soon?

**Comment by fitzgen** [comment]
Yeah, sorry been a bit busy and travelling a bunch.
