### ISSUE TITLE
Add method to return currently allocated bytes size?

### ISSUE THREAD

**Issue by novacrazy** [fitzgen/bumpalo#57]
I'm working with an application that prints diagnostic messages after running an operation to show how much memory was used during that operation, then proceeds on with the next operation. However, because the next operation relies on memory allocated in the previous operation, there are still active immutable borrows from the `Bump` allocator at the point where diagnostic information should be logged. Therefore, I cannot simply use `arena.iter_allocated_chunks().map(|chunk| chunk.len()).sum()` to return the allocated size, because that requires a mutable borrow.

Would you be willing to add a method for querying such information from an immutable `Bump` instance? Something like `Bump::allocated_bytes(&self) -> usize`

**Comment by fitzgen** [comment]
This seems reasonable to me. Would you like to make a pull request?

**Comment by novacrazy** [comment]
I'm not familiar enough with the codebase and reasoning for things enough to be confident I could write a safe implementation in the time I have. However, if you would be willing outline what it would take to make a safe implementation of such a function, I can give it a shot.

**Comment by fitzgen** [comment]
[The `dealloc_chunk_list` helper function](https://github.com/fitzgen/bumpalo/blob/9237034639142f65798b5f157b36d4aa8b766a8c/src/lib.rs#L209-L212) shows how you can iterate over each chunk. Implementing this new method should be basically the same as that, but instead of deallocating each chunk, summing each chunk's size (example of getting a chunk's size [here](https://github.com/fitzgen/bumpalo/blob/9237034639142f65798b5f157b36d4aa8b766a8c/src/lib.rs#L1016-L1022), this could be factored out to a helper method on `ChunkFooter`).

Is that enough to get you started? Anything I can clear up?
