### ISSUE TITLE
segfault only in unit test

### ISSUE THREAD

**Issue by Riey** [fitzgen/bumpalo#69]
I'm very confused and don't know what is wrong

when I run this code in unit test with `cargo test` it failed with SIGSEGV

Here is my test code
https://github.com/Riey/bumpalo/tree/unit-test-failed

![Screenshot from 2020-03-24 14-28-23](https://user-images.githubusercontent.com/14910534/77391309-ccd50780-6ddb-11ea-97b7-b125fff1cbc6.png)

but when I run same code in `main.rs` then it success

![Screenshot from 2020-03-24 14-28-54](https://user-images.githubusercontent.com/14910534/77391333-dcece700-6ddb-11ea-9f21-afa12a61d06d.png)

**Comment by Riey** [comment]
Also note that

I use Arch Linux and test failed in this line

https://github.com/fitzgen/bumpalo/blob/7d0c4ddf81aa8e5693827015ba531bf85d05a21e/src/lib.rs#L1133

**Comment by fitzgen** [comment]
Thanks for filing an issue! I can reproduce the segfault. Looking into it.

**Comment by fitzgen** [comment]
Fix incoming.

**Comment by fitzgen** [comment]
Thanks again for filing this issue!

It turns out that this is a sec bug, so I've filed this advisory: https://github.com/RustSec/advisory-db/pull/251

I've also just published 3.2.1 with the fix. See the [CHANGELOG.md](https://github.com/fitzgen/bumpalo/blob/master/CHANGELOG.md#321) and [pull request that fixes this bug](https://github.com/fitzgen/bumpalo/pull/70) for a few more details.

**Comment by Kixunil** [comment]
My understanding is that the code shouldn't read from the allocated buffer past `old_size` until it overwrites it, so it's not outright vulnerability, but increases the risk if someone screws up somewhere else. Am I correct?

**Comment by Ancient123** [comment]
@fitzgen :  3.2.1 isn't showing up in github releases or tags. Did it not actually get published yet?

**Comment by fitzgen** [comment]
@Ancient123 

> @fitzgen : 3.2.1 isn't showing up in github releases or tags. Did it not actually get published yet?

I guess I forgot to do a git tag, but the crates.io release is here: https://crates.io/crates/bumpalo/3.2.1

I'll tag it now.

----------------------

@Kixunil 

> My understanding is that the code shouldn't read from the allocated buffer past `old_size` until it overwrites it, so it's not outright vulnerability, but increases the risk if someone screws up somewhere else. Am I correct?

It would copy invalid memory into the newly allocated block. But yes, this alone is not sufficient to pull off a whole attack because it would also require some `Vec` or something to allow reading the uninitialized memory between its length and its capacity.

None the less, better safe than sorry, hence the advisory.
